### ISSUE TITLE
Instalacao no Rocky9 com problemas

### ISSUE THREAD

**Issue by inoutglobal** [neimaravila/howtos#1]
Executo a instalacao do script sudo curl -SL https://raw.githubusercontent.com/neimaravila/howtos/main/kamailio-2023/tl-dr.sh | bash
mas o kamailio nao sobe. Nao encontrei nenhum Log pra saber a causa.

![image](https://github.com/user-attachments/assets/44dd23d0-a4c8-4c22-b538-57421bb900c5)

**Comment by neimaravila** [comment]
Muito provavelmente o seu sistema não tem wget instalado.
Ajustei o script para que instale o wget.
Teste novamente.

**Comment by inoutglobal** [comment]
Boa tarde, meu caro! Nao resolveu, mesmo problema. Eu já tinha me atentado da necessidade do wget. O kamailio gera algum log que podemos verificar a causa raiz desse problema?

**Comment by inoutglobal** [comment]
Segue o log da instalacao que tentei realizar no Rocky9 em um ambiente Proxmox 7.Espero que ajude.
[instalacao kamailio.log](https://github.com/user-attachments/files/16969161/instalacao.kamailio.log)

**Comment by neimaravila** [comment]
Veja no /var/log/messages. Lá ficam as mensagens do kamailio. Peguei o mesmo script e rodei em uma maquina da GCP agora, sem problemas. Confira o status do postgresql. confirme também quais ips o script setou no kamailio.cfg, se batem com a sua interfaces.

**Comment by inoutglobal** [comment]
Mestre,

O problema era falta de memoria RAM, os logs foram certeiros. Estava com 2G de RAM e aumentei para 4G. 

![image](https://github.com/user-attachments/assets/18290459-69ad-4ba6-bc9e-27f19a90bac9)

![image](https://github.com/user-attachments/assets/cc54a540-132e-4d43-a40f-cf9bd362bae3)

**Comment by neimaravila** [comment]
Que TOP!!! Bom d+!
